# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Runs a single command using the runners shell
      - name: Install dependencies and conduct tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./
          chmod -R 755 .
          python3 piazza_test.py
          zip -r ../function.zip .
          zip -g ../function.zip lambda_function.py
          zip -g ../function.zip piazza_function.py
          zip -g ../function.zip piazza_test.py
          cd ..
          aws lambda update-function-code --function-name slackbot \
                    --zip-file fileb://function.zip
