name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Runs a single command using the runners shell
      - name: Install dependencies and conduct tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest
          pip install --target ./package requests
          cd package
          zip -r function.zip ./*
          cd ..
          zip -g package/function.zip main.py
          zip -g package/function.zip calc_test.py
          zip -g package/function.zip calc.py
          cd package
          aws lambda update-function-code --function-name bscs-capstone \
                    --zip-file fileb://function.zip


